#!/bin/bash
#SBATCH --job-name=maprnaseq1
#SBATCH --partition=batch
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=ad45368@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64gb
#SBATCH --time=8:00:00
#SBATCH --output=../MappingOutput/logs/MapRNAseq.%j.out
#SBATCH --error=../MappingOutput/logs/MapRNAseq.%j.err

cd $SLURM_SUBMIT_DIR

THREADS=2

###ADD a source file with path to FastqF* iles
#variables imported from submission script
# accession=SRR#

#fastqPath=Path to folder containing folders of accessions, each containing one fastq; these are generated by ffq (https://github.com/UGALewisLab/downloadSRA.git)
#outdir=this is ../MappingData


#pipeaccession summary: trim reads, map with STAR, get Counts

#notes
# #generated a STAR genome index with the following call:
# STAR --runMode genomeGenerate --runThreadN 1 --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR --genomeFastaFiles /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_00182925.2plusHphplusBarplusTetO.fna --sjdbGTFfile /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic_WithExtras_GFFtoGTFconversion.gtf
# need to rerun with normal genome assembly. The his-3 duplicated region will create multi-mappers
#

###################
#start
####################################################

###################################
#input file variables. first check for accessions that have separate folders.
  read1=${fastqPath}/${accession}_1.fastq.gz
  read2=${fastqPath}/${accession}_2.fastq.gz

# make variables for other reads that are dumped together. my sample names are formated like this: OE1_S0_L001_R1_001.fastq.gz
  read1b=${fastqPath}/${accession}_R1_001.fastq.gz
  read2b=${fastqPath}/${accession}_R2_001.fastq.gz

#make output file folders
name=$(echo "$accession" | sed -E 's/_S[0-9]{1,3}_L[0-9]{3}//')
trimmed="${outdir}/TrimmedFastQs"
mkdir $trimmed

bamdir="${outdir}/bamFiles/${name}"
mkdir "${bamdir}"

countsdir="${outdir}/counts"
mkdir "${countsdir}"

bwDir="${outdir}/bigWig"
mkdir "${bwDir}"

mkdir ${outdir}/condensed

#make variables for output file names
bam="${bamdir}/${name}_"
counts="${countsdir}/${name}_counts.txt"
bw="${bwDir}/${name}.bw"

mkdir ${outdir}/counts2
counts2="${outdir}/counts2/${name}_fungidb_counts.txt"

# make vars for editing detection
#bam=${bamPath}/${accession}_Aligned.sortedByCoord.out.bam

#make output file folders
deduped_dir=${outdir}/DedupedBams
mkdir ${deduped_dir}

split_reads=${outdir}/SplitBams
mkdir ${split_reads}

tables=${outdir}/EditTables
mkdir ${tables}

tmpdir=${outdir}/Temp
mkdir $tmpdir

tmp=${tmpdir}/${accession}_tmp.bam
tmp2=${tmpdir}/${accession}_tmp2.bam
tmp3=${tmpdir}/${accession}_tmp3.bam

deduped=${deduped_dir}/${name}_deduped.bam

forward=${split_reads}/${name}_sense.bam
reverse=${split_reads}/${name}_antisense.bam

############# Read Trimming ##############
#remove adaptors, trim low quality reads (default = phred 20), length > 25

##fastq files from the ebi link are in folders that either have one file with a SRR##.fastq.gz or a SRR##_1.fastq.gz ending, or have two files with a SRR##_1.fastq.gz ending or a SRR##_2.fastq.gz ending
#or have three files with a SRR##_1.fastq.gz, SRR##_2.fastq.gz and SRR##.fastq.gz ending. In this case, the third file corresponds to unpaired reads that the depositers mapped.



#if read1 file does not exist, do single-end trimming using the only file in the folder i.e. SRR##.fastq.gz filename format
##This entire section can be simplified for JGI data

# if [ ! -f $read1 ]; then
# #trim reads
#   echo "${line} fsd1 sample!"
#
#   module load Trim_Galore/0.6.10-GCCcore-12.3.0
#
# trim_galore --illumina --fastqc --paired --length 25 --basename ${name} --gzip -o $trimmed $read1b $read2b
#   wait
#
#
# ##map with STAR
#
#   module load STAR/2.7.10b-GCC-11.3.0
#     STAR --runMode alignReads \
#   --runThreadN $THREADS \
#   --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR \
#   --outFileNamePrefix ${bam} \
#   --readFilesIn $trimmed/${name}_val_1.fq.gz $trimmed/${name}_val_2.fq.gz \
#   --readFilesCommand zcat \
#   --alignIntronMax 10000 \
#   --outSAMtype BAM SortedByCoordinate \
#   --outBAMsortingBinsN 100 \
#   --outSAMunmapped Within \
#   --outSAMattributes Standard \
#   --limitBAMsortRAM 20455724800
#
#
#    # create index
#     module load SAMtools/1.21-GCC-13.3.0
#     samtools index "${bam}Aligned.sortedByCoord.out.bam"
#
#     ##quantify with featureCounts
#     module load Subread/2.0.6-GCC-12.3.0
#
#     featureCounts -T $THREADS \
#     -t CDS \
#     -g gene_name \
#     -s 0 --primary \
#     --countReadPairs -p \
#     -a /home/ad45368/NcGenome/fungiDB_GFFtoGTF_conversion.gtf  \
#     -o $counts \
#     ${bam}Aligned.sortedByCoord.out.bam
#
#     cp ${bam}Aligned.sortedByCoord.out.bam ${outdir}/bamFiles
#
#     ##Plot reads to visualize tracks if needed
#        module load deepTools/3.5.5-gfbf-2023a
#          #Plot all reads
#        bamCoverage -p $THREADS -bs 50 --normalizeUsing BPM -of bigwig -b "${bam}Aligned.sortedByCoord.out.bam" -o "${bw}"
#
#
#
# #elseif read2 exists, do paired-end Trimming and PE mapping
# elif [ -f $read2 ]; then
#   echo "${line} SRR file!"
#
#
#   ##################
#   #Trimming
#   #################
#   	  module load Trim_Galore/0.6.10-GCCcore-12.3.0
#
#  	  trim_galore --illumina --fastqc --paired --length 25 --basename ${name} --gzip -o $trimmed $read1 $read2
#   	  wait
#
#
#   ##map with STAR
#
#   	  module load STAR/2.7.10b-GCC-11.3.0
#   	  STAR --runMode alignReads \
#  	    --runThreadN $THREADS \
#  	    --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR \
#  	    --outFileNamePrefix ${bam} \
#  	    --readFilesIn $trimmed/${name}_val_1.fq.gz $trimmed/${name}_val_2.fq.gz \
#  	    --readFilesCommand zcat \
#       --alignIntronMax 10000 \
#   	  --outSAMtype BAM SortedByCoordinate \
#       --outBAMsortingBinsN 100 \
#       --outSAMunmapped Within \
#       --outSAMattributes Standard \
#       --limitBAMsortRAM 20455724800
#
#
#        # create index
#         module load SAMtools/1.21-GCC-13.3.0
#         samtools index "${bam}Aligned.sortedByCoord.out.bam"
#
#         ##quantify with featureCounts
#         module load Subread/2.0.6-GCC-12.3.0
#
#         featureCounts -T $THREADS \
#         -t CDS \
#         -g gene_name \
#         -s 0 --primary \
#         --countReadPairs -p \
#         -a /home/ad45368/NcGenome/fungiDB_GFFtoGTF_conversion.gtf  \
#         -o $counts \
#         ${bam}Aligned.sortedByCoord.out.bam
#
#         cp ${bam}Aligned.sortedByCoord.out.bam ${outdir}/bamFiles
#
#         ##Plot reads to visualize tracks if needed
#            module load deepTools/3.5.5-gfbf-2023a
#              #Plot all reads
#            bamCoverage -p $THREADS -bs 50 --normalizeUsing BPM -of bigwig -b "${bam}Aligned.sortedByCoord.out.bam" -o "${bw}"
# fi

ml GCC/11.3.0
ml SAMtools/1.16.1-GCC-11.3.0
# ml BWA/0.7.18-GCCcore-13.3.0
ml picard/3.3.0-Java-17
ml R/4.4.2-gfbf-2024a

# echo "Step 1: Checking and fixing read names..."
# samtools view -h ${bam}Aligned.sortedByCoord.out.bam | \
#   awk 'BEGIN {FS=OFS="\t"; c=1}
#   /^@/ { print; next }
#   {
#     # Ensure read name has required format for MarkDuplicates
#     # STAR output: SRR#.position or similar
#     # Picard expects: name:tile:x:y:duplicate
#     if ($1 !~ /:[0-9]+:[0-9]+:[0-9]+/) {
#       # Add dummy tile:x:y:dup
#       $1 = $1 ":0:0:0:" (c % 2)
#       c++
#     }
#     print
#   }' | samtools view -b -o ${tmp} -
#
# samtools addreplacerg -r "@RG\tID:RG1\tSM:SampleName\tPL:Illumina\tLB:Library" -o ${tmp2} ${tmp}
# samtools sort ${tmp2} -o ${tmp3}
#
# java -jar $EBROOTPICARD/picard.jar MarkDuplicates \
#     --INPUT ${tmp3} \
#     --OUTPUT ${deduped} \
#     -M ${deduped_dir}/${accession}.marked_dup_metrics.txt \
#     --OPTICAL_DUPLICATE_PIXEL_DISTANCE -1 --REMOVE_DUPLICATES TRUE
#
#     #index again
#     samtools index -@ $THREADS ${deduped}
#
#
#     # split forward and reverse reads
#     ml BamTools/2.5.2-GCC-11.3.0
#
#     bamtools filter -script filter_forward.txt -in ${deduped} -out ${forward}
#       samtools index -@ $THREADS ${forward}
#
#     bamtools filter -script filter_rev.txt -in ${deduped} -out ${reverse}
#       samtools index -@ $THREADS ${reverse}
#
   # create virtual environment for REDItools
   ml Python/3.10.4-GCCcore-11.3.0
   ml HTSlib/1.15.1-GCC-11.3.0

 . ~/env/python_REDItools/bin/activate

 python ~/reditools2.0/src/cineca/reditools.py -f ${forward} \
  -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
  -o ${tables}/${name}_forward_edits.gz \
  -q 25 \                    # min-read-quality (mapping quality)
  -bq 25 \                   # min-base-quality
  -l 10 \                    # min-column-length (coverage)
  -me 3 \                    # min-edits (matches -v 3)
#  -men 0.03 \                # min-edits-per-nucleotide (matches -n 0.03)
  -mbp 6 \            # trim bases (matches -a 6-0)
  -s 2 -S \
  # strand inference and correction
 python ~/reditools2.0/src/cineca/reditools_table_to_bed.py  -i ${tables}/${name}_forward_edits.txt -o ${tables}/${name}_forward_edits.bed  
	
#  python ~/reditools2.0/src/cineca/reditools.py -f ${reverse} \
#  -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
#  -o ${tables}/${name}_reverse_edits.txt \
#  -q 25 \                    # min-read-quality (mapping quality)
#  -bq 25 \                   # min-base-quality
#  -l 10 \                    # min-column-length (coverage)
#  -me 3 \                    # min-edits (matches -v 3)
#  -men 0.03 \                # min-edits-per-nucleotide (matches -n 0.03)
#  -mbp 6 \
#  -Mbp 0 \            # trim bases (matches -a 6-0)
#  -s 1   \
   # strand inference and correction

deactivate
