#!/bin/bash
#SBATCH --job-name=call_ai
#SBATCH --partition=batch
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=YOUREMAIL@EMAIL.COM
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=20gb
#SBATCH --time=8:00:00
#SBATCH --output=../MappingOutput/logs/atoi.%j.out
#SBATCH --error=./MappingOutput/logs/atoi.%j.err

cd $SLURM_SUBMIT_DIR

THREADS=2

## these variables will read in from an input file; setting directly for testing.
outdir=/scratch/ad45368/fsd1/MappingOutput
bamPath=/scratch/ad45368/fsd1/MappingOutput/bamFiles


###ADD a source file with path to FastqF* iles
#variables imported from submission script
# accession=SRR#

#fastqPath=Path to folder containing folders of accessions, each containing one fastq; these are generated by ffq (https://github.com/UGALewisLab/downloadSRA.git)
#outdir=this is ../MappingData


#pipeaccession summary: trim reads, map with STAR, get Counts

#notes
# #generated a STAR genome index with the following call:
# STAR --runMode genomeGenerate --runThreadN 1 --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR --genomeFastaFiles /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_00182925.2plusHphplusBarplusTetO.fna --sjdbGTFfile /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic_WithExtras_GFFtoGTFconversion.gtf
# need to rerun with normal genome assembly. The his-3 duplicated region will create multi-mappers
#

###################
#start
####################################################

###################################
#input file variables
  bam=${bamPath}/${accession}_Aligned.sortedByCoord.out.bam

#make output file folders
name=$(echo "$accession" | sed -E 's/_S[0-9]{1}_L[0-9]{3}//')

deduped_dir=${outdir}/DedupedBams
mkdir ${deduped_dir}

split_reads=${outdir}/SplitBams
mkdir ${split_reads}

tables=${outdir}/EditTables
mkdir ${tables}

tmp=${deduped_dir}/${accession}_tmp.bam
deduped=${deduped_dir}/${accession}_deduped.bam

forward=${split_reads}/${accession}_sense.bam
reverse=${split_reads}/${accession}_antisense.bam
# remove duplicates from bam file
 ml SAMtools/1.21-GCC-13.3.0
 ml BWA/0.7.18-GCCcore-13.3.0
 ml picard/3.3.0-Java-17
 ml R/4.4.2-gfbf-2024a
 
 samtools addreplacerg -r "@RG\tID:RG1\tSM:SampleName\tPL:Illumina\tLB:Library.fa" -o ${tmp} $bam

  java -jar $EBROOTPICARD/picard.jar MarkDuplicates \
      --INPUT ${tmp} \
      --OUTPUT ${deduped} \
      -M ${deduped_dir}/${accession}.marked_dup_metrics.txt \
      --REMOVE_DUPLICATES TRUE

 #index again
 samtools index -@ $THREADS ${deduped}
 rm ${tmp}

 # split forward and reverse reads
 ml BamTools/2.5.2-GCC-13.3.0

 bamtools filter -script filter_fwd.txt -in ${deduped} -out ${forward}
   samtools index -@ $THREADS ${forward}

 bamtools filter -script filter_rev.txt -in ${deduped} -out ${reverse}
   samtools index -@ $THREADS ${reverse}

# create virtual environment for REDItools
ml Python/3.11.3-GCCcore-12.3.0
ml HTSlib/1.9-GCC-11.2.0
# python -m venv ~/env/python_REDItools

#git clone https://github.com/tflati/reditools2.0.git
#cd reditools2.0

 #pip install -r requirements.txt
 #pip install --upgrade pip
 
 . ~/env/python_REDItools/bin/activate

 python ~/reditools2.0/src/cineca/reditools.py -f ${forward} -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna  -o ${tables}/${accession}_forward_edits.txt -q 25 -bq 25 -me 3 -mbp 7
 python  ~/reditools2.0/src/cineca/reditools.py -f ${reverse} -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna  -o ${tables}/${accession}_reverse_edits.txt -q 25 -bq 25 -me 3 -mbp 7

deactivate

 
