#!/bin/bash
#SBATCH --job-name=redi1
#SBATCH --partition=batch
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=ad45368@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=64gb
#SBATCH --time=8:00:00
#SBATCH --output=../RNAseq_Output/logs/mapREDI1.%j.out
#SBATCH --error=../RNAseq_Output/logs/mapREDI1.%j.err


cd $SLURM_SUBMIT_DIR

THREADS=12
GENOME="/home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic"


###ADD a source file with path to FastqF* iles
#variables imported from submission script
# accession=SRR#

#fastqPath=Path to folder containing folders of accessions, each containing one fastq; these are generated by ffq (https://github.com/UGALewisLab/downloadSRA.git)
#outdir=this is ../MappingData


#pipeaccession summary: trim reads, map with STAR, get Counts

#notes
# #generated a STAR genome index with the following call:
# STAR --runMode genomeGenerate --runThreadN 1 --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR --genomeFastaFiles /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_00182925.2plusHphplusBarplusTetO.fna --sjdbGTFfile /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic_WithExtras_GFFtoGTFconversion.gtf
# need to rerun with normal genome assembly. The his-3 duplicated region will create multi-mappers
#

###################
#start
####################################################

###################################
#input file variables. first check for accessions that have separate folders.
  read1=${fastqPath}/${accession}_1.fastq.gz
  read2=${fastqPath}/${accession}_2.fastq.gz

# make output file folders
trimmed="${outdir}/TrimmedFastQs"
mkdir -p "$trimmed"

## setting variables
bamdir="${outdir}/bamFiles"
mkdir -p "$bamdir"
bam="${bamdir}/${name}_"

countsdir="${outdir}/counts"
mkdir -p "${countsdir}"

bwDir="${outdir}/bigWig"
mkdir -p "${bwDir}"

bam="${bamdir}/${name}_"
counts="${countsdir}/${name}_counts.txt"
bw="${bwDir}/${name}.bw"

## Set variables for editing analysis
  # set genomic DNA control accession
  control=${control:-156_fsd1GFP_OX2}

  deduped_dir=${outdir}/DedupedBams
  mkdir -p "${deduped_dir}"
  deduped=${deduped_dir}/${name}_deduped.bam

  tmpdir=${outdir}/tempFiles
  mkdir -p "${tmpdir}"
    tmp=${tmpdir}/${accession}_tmp.bam
    tmp2=${tmpdir}/${accession}_tmp2.bam
    tmp3=${tmpdir}/${accession}_tmp3.bam

  split_reads=${outdir}/SplitBams
  mkdir -p "${split_reads}"
    forward=${split_reads}/${name}_sense.bam
    reverse=${split_reads}/${name}_antisense.bam


  tables=${outdir}/EditTables
  mkdir -p "${tables}"
    forward_table=${tables}/${name}_forward_edits.txt
    reverse_table=${tables}/${name}_reverse_edits.txt


##### PART 1: MAPPING #####

### First check for DNA WGS samples, for A-to-I background mapping. If it is a DNA sample, trim reads and map using BWA then skip to editing section.
  echo "mapping ${accession} DNA control sample!"

  dna_read1=${fastqPath}/${accession}_R1_001.fastq.gz
  dna_read2=${fastqPath}/${accession}_R2_001.fastq.gz

dna_name=$(echo "$accession" | sed -E 's/_S[0-9]{1,3}_L[0-9]{3}//')
dna_bam="${bamdir}/${dna_name}.bam"

module load Trim_Galore/0.6.10-GCCcore-12.3.0
  trim_galore --illumina --fastqc --paired --length 25 --basename ${dna_name} --gzip -o $trimmed $dna_read1 $dna_read2
  wait

ml SAMtools/1.21-GCC-13.3.0
ml BWA/0.7.18-GCCcore-13.3.0
bwa mem -M -v 3 -t $THREADS $GENOME ${trimmed}/${dna_name}_val_1.fq.gz ${trimmed}/${dna_name}_val_2.fq.gz | samtools view -bhSu - | samtools sort -@ $THREADS -T $tmp -o "$dna_bam" -
  samtools index -@ $THREADS "${dna_bam}"

## use reditools1
# ml Python/2.7.18-GCCcore-13.3.0

# python -m virtualenv ~/env/REDItools1
. ~/env/REDItools1/bin/activate
#   pip install pysam

  REDItoolDnaRna.py -i ${forward} -j ${split_reads}/${control}_sense.bam \
    -f ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
    -o ${tables}/${name}_fwd \
    -k exclude.bed \
        -o ${tables}/${name}_fwd \
        -k exclude.bed \
        -t 12 \
        -m 20,20 -q 25,25 -c 10,10 \
         -v 3 -n 0.03 -a 6-0 -z -e -u \
        -s 1 -S

    REDItoolDnaRna.py -i ${reverse} -j ${split_reads}/${control}_antisense.bam \
      -f ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
      -o ${tables}/${name}_rev \
      -k exclude.bed \
      -t 12 \
      -m 20,20 -q 25,25 -c 10,10 \
      -v 3 -n 0.03 -a 6-0 -z -e -u \
      -s 2 -S
