#!/bin/bash
#SBATCH --job-name=call_ai
#SBATCH --partition=batch
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=YOUREMAIL@EMAIL.COM
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=60gb
#SBATCH --time=8:00:00
#SBATCH --output=../MappingOutput/logs/atoi.%j.out
#SBATCH --error=./MappingOutput/logs/atoi.%j.err

cd $SLURM_SUBMIT_DIR

THREADS=2

## these variables will read in from an input file; setting directly for testing.
outdir=/scratch/ad45368/fsd1/MappingOutput
bamPath=/scratch/ad45368/fsd1/MappingOutput/bamFiles


###ADD a source file with path to FastqF* iles
#variables imported from submission script
# accession=SRR#

#fastqPath=Path to folder containing folders of accessions, each containing one fastq; these are generated by ffq (https://github.com/UGALewisLab/downloadSRA.git)
#outdir=this is ../MappingData


#pipeaccession summary: trim reads, map with STAR, get Counts

#notes
# #generated a STAR genome index with the following call:
# STAR --runMode genomeGenerate --runThreadN 1 --genomeDir /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/STAR --genomeFastaFiles /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_00182925.2plusHphplusBarplusTetO.fna --sjdbGTFfile /home/zlewis/Genomes/Neurospora/Nc12_RefSeq/GCA_000182925.2_NC12_genomic_WithExtras_GFFtoGTFconversion.gtf
# need to rerun with normal genome assembly. The his-3 duplicated region will create multi-mappers
#

###################
#start
####################################################

###################################
#input file variables
  bam=${bamPath}/${accession}_Aligned.sortedByCoord.out.bam

#make output file folders
name=$(echo "$accession" | sed -E 's/_S[0-9]{1}_L[0-9]{3}//')

deduped_dir=${outdir}/DedupedBams
mkdir ${deduped_dir}

split_reads=${outdir}/SplitBams
mkdir ${split_reads}

tables=${outdir}/EditTables
mkdir ${tables}

tmp=${deduped_dir}/${accession}_tmp.bam
deduped=${deduped_dir}/${accession}_deduped.bam

forward=${split_reads}/${accession}_sense.bam
reverse=${split_reads}/${accession}_antisense.bam
# remove duplicates from bam file
ml GCC/11.3.0
 ml SAMtools/1.16.1-GCC-11.3.0
# ml BWA/0.7.18-GCCcore-13.3.0
 ml picard/3.3.0-Java-17
 ml R/4.4.2-gfbf-2024a

echo "Step 1: Checking and fixing read names..."
samtools view -h ${bam} | \
  awk 'BEGIN {FS=OFS="\t"; c=1} 
  /^@/ { print; next }
  {
    # Ensure read name has required format for MarkDuplicates
    # STAR output: SRR#.position or similar
    # Picard expects: name:tile:x:y:duplicate
    if ($1 !~ /:[0-9]+:[0-9]+:[0-9]+/) {
      # Add dummy tile:x:y:dup
      $1 = $1 ":0:0:0:" (c % 2)
      c++
    }
    print
  }' | samtools view -b -o ${tmp}.fixed.bam -

bam=${tmp}.fixed.bam

# Then continue with addreplacerg and MarkDuplicates
samtools addreplacerg -r "@RG\tID:RG1\tSM:SampleName\tPL:Illumina\tLB:Library" -o ${tmp} ${bam}
samtools sort ${tmp} -o ${deduped_dir}/${accession}_sorted.tmp.bam

  
  java -jar $EBROOTPICARD/picard.jar MarkDuplicates \
      --INPUT ${deduped_dir}/${accession}_sorted.tmp.bam \
      --OUTPUT ${deduped} \
      -M ${deduped_dir}/${accession}.marked_dup_metrics.txt \
      --OPTICAL_DUPLICATE_PIXEL_DISTANCE -1 \ 
      --REMOVE_DUPLICATES TRUE

 #index again
 samtools index -@ $THREADS ${deduped}
 rm ${tmp}

 # split forward and reverse reads
 ml BamTools/2.5.2-GCC-11.3.0

 bamtools filter -script filter_fwd.txt -in ${deduped} -out ${forward}
   samtools index -@ $THREADS ${forward}

 bamtools filter -script filter_rev.txt -in ${deduped} -out ${reverse}
   samtools index -@ $THREADS ${reverse}

# create virtual environment for REDItools
ml Python/3.10.4-GCCcore-11.3.0
ml HTSlib/1.15.1-GCC-11.3.0
# python -m venv ~/env/python_REDItools

#git clone https://github.com/tflati/reditools2.0.git
#cd reditools2.0

 #pip install -r requirements.txt
 #pip install --upgrade pip
 
 . ~/env/python_REDItools/bin/activate

 python ~/reditools2.0/src/cineca/reditools.py -f ${forward} \
  -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
  -o ${tables}/${accession}_forward_edits.txt \
  -q 25 \                    # min-read-quality (mapping quality)
  -bq 25 \                   # min-base-quality
  -l 10 \                    # min-column-length (coverage)
  -me 3 \                    # min-edits (matches -v 3)
  -men 0.03 \                # min-edits-per-nucleotide (matches -n 0.03)
  -mbp 6 -Mbp 0 \            # trim bases (matches -a 6-0)
  -s 1 -C                    # strand inference and correction

  python ~/reditools2.0/src/cineca/reditools.py -f ${reverse} \
  -r ~/NcGenome/GCA_000182925.2_NC12_genomic.fna \
  -o ${tables}/${accession}_reverse_edits.txt \
  -q 25 \                    # min-read-quality (mapping quality)
  -bq 25 \                   # min-base-quality
  -l 10 \                    # min-column-length (coverage)
  -me 3 \                    # min-edits (matches -v 3)
  -men 0.03 \                # min-edits-per-nucleotide (matches -n 0.03)
  -mbp 6 -Mbp 0 \            # trim bases (matches -a 6-0)
  -s 1 -C                    # strand inference and correction

deactivate

 
